[package]
name = "tlsn-verifier"
authors = ["TLSNotary Team"]
description = "Contains the verifier library"
keywords = ["tls", "mpc", "2pc", "verifier"]
categories = ["cryptography"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tlsn-core.workspace = true
tlsn-tls-core.workspace = true
tlsn-utils.workspace = true

mpz-core.workspace = true

webpki-roots.workspace = true
p256.workspace = true
thiserror.workspace = true
