[build]
target = "wasm32-unknown-unknown"
#target = "x86_64-unknown-linux-gnu"

[target.wasm32-unknown-unknown]
rustflags = [
    "-C",
    "target-feature=+atomics,+bulk-memory,+mutable-globals",
]

[unstable]
build-std = ["panic_abort", "std"]